### ISSUE TITLE
654번줄 오타 수정

### ISSUE THREAD

**Issue by wooogi123** [buttercrab/wtfpython-ko#1]
654라인 yeild 를 yield로 수정해야 합니다.
번역 계속 진행 중 이시면 같이 작업할 수 있을까요?

**Comment by buttercrab** [comment]
@wooogi123 늦어서 죄송합니다. 지금 학생이라서 번역이 느리기는 하지만 진행중입니다. 같이 작업하는 것은 언제든지 찬성입니다!
