### ISSUE TITLE
원본과는 다른 ▶ 아이콘

### ISSUE THREAD

**Issue by buttercrab** [buttercrab/wtfpython-ko#15]
▶ 아이콘이 [원본](https://github.com/satwikkansal/wtfpython)과는 다르게 나옵니다.

[중국어 번역](https://github.com/leisurelicht/wtfpython-cn)을 보니 > 문자를 사용했습니다.

| 이 레포지토리 | 원본 |
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/34997549/79059517-f9cb5a80-7cb5-11ea-9085-07a50091cb49.png)|![image](https://user-images.githubusercontent.com/34997549/79059531-0f408480-7cb6-11ea-9d14-50d196256219.png)|

**Comment by wooogi123** [comment]
[원본](https://raw.githubusercontent.com/satwikkansal/wtfpython/master/README.md)도 이 [repo](https://raw.githubusercontent.com/wooogi123/wtfpython-ko/3.0/README.md)와 마찬가지로 ▶ 아이콘으로 되어있는 것 같습니다. 
중국어 번역이 > 문자로 아이콘이 다르게 되어있는 것 같은데 확인해주시겠어요?

**Comment by buttercrab** [comment]
원본과는 같은 아이콘인데 보여지는 모습이 달라서 이슈를 만들었습니다.
중국어 번역도 아마 이걸 보고 >로 바꾼 것 같습니다.

**Comment by wooogi123** [comment]
raw 상으로는 같은 아이콘이라 저는 구태여 손 댈 필요가 없다고 생각하는데 다른 분들 의견도 들어보고 결정하면 될거같네요.

**Comment by buttercrab** [comment]
지금 보니까 원본도 바뀌어 있네요. 원본도 바뀌면 그때 이슈를 다시 열겠습니다.
